### ISSUE TITLE
2015 update available

### ISSUE THREAD

**Issue by seanlahman** [cdalzell/Lahman#17]
2015 data is now available, either through [Github](https://github.com/chadwickbureau/baseballdatabank) or my website: [http://seanlahman.com](http://seanlahman.com)

**Comment by friendly** [comment]
Thanks for the notice, Sean.
Could you, or someone else look over issues #13, #14, and #16 in our repo
and let us know which of these can be considered closed?

**Comment by seanlahman** [comment]
Will do.

**Comment by cdalzell** [comment]
Feature branch created: https://github.com/cdalzell/Lahman/tree/feature/2015-data-update

**Comment by cdalzell** [comment]
Just a quick FYI, I've been holding off on updating as there's still cleanup going on with the new data set: https://github.com/chadwickbureau/baseballdatabank/issues

**Comment by friendly** [comment]
Just as well.  We don't want risk having to do it over again.

**Comment by cdalzell** [comment]
Successfully submitted to CRAN
