### ISSUE TITLE
move baseballdatabank-master/ out of data/

### ISSUE THREAD

**Issue by friendly** [cdalzell/Lahman#18]
I tried R cmd check in a local clone of the `feature/2015-data-update`.  It gives a warning on `baseballdatabank-master`:

    * checking contents of 'data' directory ... WARNING
    Files not of a type allowed in a 'data' directory:
      'baseballdatabank-master'
    Please use e.g. 'inst/extdata' for non-R data files
    * checking data for non-ASCII characters ... OK
    * checking data for ASCII and uncompressed saves ... OK
    * checking examples ... OK
    * DONE
    Status: 1 WARNING, 1 NOTE

**Comment by cdalzell** [comment]
Thank you, @friendly!
