### ISSUE TITLE
Incorrect birthDate for johnsbi01

### ISSUE THREAD

**Issue by cdalzell** [cdalzell/Lahman#27]
Data issue reported via email, confirmed in latest version.

```r
library(Lahman)
library(dplyr)

Lahman::Master %>%
  filter(playerID == "johnsbi01") %>%
  select(playerID, nameFirst, nameLast, birthDate, debut) %>%
  mutate(debut_age = as.Date(debut) - as.Date(birthDate))
```

I'm reasonably sure no one has ever debuted in the MLB at -28216 days old.. :)

I'm seeing that there's a ton of work currently underway in our upstream data source. I'll submit a fix PR if that's not already fixed before this year's update is submitted to CRAN.

**Comment by seanlahman** [comment]
Thanks for sharing. This has been fixed in the baseball databank.  Birth year should be 1861, not 1961.

**Comment by cdalzell** [comment]
Yep, just verified it myself with the latest upstream. :)

Thanks again for all your hard work and please let me know if there's anything I can do to help.
