### ISSUE TITLE
Branches need some pruning

### ISSUE THREAD

**Issue by friendly** [cdalzell/Lahman#29]
Looking at the github repo, there is an awful lot of cruft branches that go back to release/v.3.0-0.
I guess we should maintain the release branches, but what about the various feature/ branches
and dm- branches?

**Comment by cdalzell** [comment]
I deleted most of the feature branches and release branches as those can be tracked using tags (https://github.com/cdalzell/Lahman/tags).

The ones I left have some help page and example updates that don't seemed to have been touched in a year, so I'll create a new feature branch and merge those in if they've not been merged in already.

**Comment by cdalzell** [comment]
Merged the remaining branches to make sure no updates got lost in the shuffle (There ended up being none). Also deleted the remaining unneeded branches.
