### ISSUE TITLE
OOTP Data Integration

### ISSUE THREAD

**Issue by cdalzell** [cdalzell/Lahman#3]
I think it would be neat if it were possible to load and append [OOTP](http://www.ootpdevelopments.com/out-of-the-park-baseball/) (Out Of The Park Baseball) save game stats.

This is an extreme stretch goal and I have no idea if it's even feasible as I'm not even slightly familiar with the internals of OOTP saves.

**Comment by mpaarating** [comment]
This is a truly beautiful idea.

**Comment by friendly** [comment]
I think this is a topic for a different package.  The goal for the Lahman package should be to faithfully reflect the historical data in the Lahman database, and perhaps provide some useful tools or examples.
But it should not be construed as a package for all things baseball.

**Comment by cdalzell** [comment]
@friendly That's a fair point..
