### ISSUE TITLE
Testing the Release v.6.0-0 branch

### ISSUE THREAD

**Issue by friendly** [cdalzell/Lahman#30]
Within R Studio, I ran build->check.  Looks good, but there is one NOTE and a comment that may trigger a reply from the CRAN gateway-keeper:

    * checking installed package size ... NOTE
      installed size is  7.4Mb
      sub-directories of 1Mb or more:
        data   7.2Mb

This is standard, since it is mainly a data package.  this is already addressed in the `cran-comments.md` file.

We also get a comment at the end that the Pitching examples take longer than 5 sec to run.

    * checking examples ... OK
    Examples with CPU or elapsed time > 5s
             user system elapsed
    Pitching 4.96   0.22    5.18
    * DONE

**Comment by cdalzell** [comment]
v6 has been accepted to CRAN, think we're good now!

**Comment by friendly** [comment]
@cdalzell 
Thanks for cleaning up the issues.  We haven't had many, but it is in keeping with tidy practices and github hygiene to close those we are done with.
