### ISSUE TITLE
erroneous dates in Master

### ISSUE THREAD

**Issue by beanumber** [cdalzell/Lahman#31]
`johnsbi01` was born in 1961 and died in 1942? According to (https://en.wikipedia.org/wiki/Lefty_Johnson) he was born in 1862.

**Comment by cdalzell** [comment]
This is corrected in the new version of this package which should be available on CRAN very soon. In the meantime then newest version can be loaded using dev_tools from this branch: https://github.com/cdalzell/Lahman/tree/release/6.0-0.

To be more specific about the change, it was updated to 9/28/1861, which matches what's listed in Baseball Reference: https://www.baseball-reference.com/players/j/johnsbi01.shtml

**Comment by beanumber** [comment]
Thanks!
