### ISSUE TITLE
Missing table - FieldingOFsplit

### ISSUE THREAD

**Issue by bdilday** [cdalzell/Lahman#32]
It looks like the table `FieldingOFsplit` is missing. I think you need it to cover OF splits for years subsequent to 1955.

**Comment by friendly** [comment]
Thanks for point this out.

For clarity: you are referring to the following from the file, [readme2016.txt](http://seanlahman.com/files/database/readme2016.txt)

    Three new tables have been introduced: FieldingOFsplit, Parks, and HomeGames

Our update for 2016 included all updates to the previously existing tables, but did not include the new tables, which are something of a larger re-organization of the database. How and when we incorporate this into the `Lahman` package will take more thought and effort.
