### ISSUE TITLE
Vignettes: payroll

### ISSUE THREAD

**Issue by MonkmanMH** [cdalzell/Lahman#42]
The "payroll.Rmd" file does not knit; there is an error at line 210, in the car::Boxplot() function. I'm not familiar with the package, and can't diagnose the source of the error.

**Comment by friendly** [comment]
`car::Boxplot` and other functions in the `car` package were reorganized in the latest version.  I'll check & fix this.

**Comment by friendly** [comment]
Just to be clear: are you referring to the `vignettes` branch?

**Comment by friendly** [comment]
Closing #42

**Comment by MonkmanMH** [comment]
Thanks! And yes, I meant the `vignettes` branch.
