### ISSUE TITLE
Preparing for v. 7.0 release

### ISSUE THREAD

**Issue by friendly** [cdalzell/Lahman#43]
I'm looking at the branches with a view to preparing for the v. 7.0 release.  A major feature will be the inclusion of vignettes, now all on the `vignettes` branch.  This branch is now ~11 commits ahead of `master` and 6 commits behind.  There will be more work on the `vignettes` branch as we go forward.

I'm not sure how to manage this on GitHub with a PR to `master`.  Hopefully, there are no conflicts, so a fast-forward will work.

I think, but am not sure, that Chris' initial work with the 2017 data bases are on a `feature/` branch.

**Comment by cdalzell** [comment]
Branch in question is here: https://github.com/cdalzell/Lahman/tree/feature/%2338-2017_Update

Hope to have to 2017 update done ASAP.
