### ISSUE TITLE
Updating for the v 7.0 releasse

### ISSUE THREAD

**Issue by friendly** [cdalzell/Lahman#45]

**Comment by friendly** [comment]
For continuity of issues, I'm posting here the email from @cdalzell on 12/31/2018:

> Started digging in on this a bit ago and discovered a pretty significant change. The "Master" table is now called "People" with exactly the same content.
> 
> Simply renaming the data is almost certainly going be a significant breaking change to anything that uses this library. Here's my proposal on how to proceed:
> 
>     Create the People table
>     Copy the People table to Master
>     Indicate via the man file and README that Master is deprecated and will be removed at some point in the future.
>     It would be nice to be able to add something  to Master so a deprecation warning is displayed when used but I don't know off the top of my head how to do that or if that's even possible without a ton of effort.
> 
> Another possibility is to just rename Player to Master.. I'm curious to hear everyone's thoughts on all this.

**Comment by friendly** [comment]
This is a fairly significant change and affects all the documentation where `Master` is used, but should become `People`.  I think @cdalzell is largely right:  A simple rename of `Master -> People` would break too many existing uses, ours and by others.

Assuming the content (variables) in `People` is identical to that in `Master` of v. 6.0, I agree that we should have these as duplicates under different names in v. 7.0, with updates to the man files and README.

Unfortunately, I don't know of any way to deprecate a data set so a warning is produced when that
data set is loaded.

**Comment by friendly** [comment]
@cdalzell Can this step go ahead in the `feature/#38-2017_update` branch? This branch is 8 commits ahead, 6 commits behind master.

**Comment by cdalzell** [comment]
Now that work is underway on v8, does anyone have any thoughts on how to move forward or the possibility of removing `Master` altogether?
