### ISSUE TITLE
Migrate package url from R-Forge

### ISSUE THREAD

**Issue by friendly** [cdalzell/Lahman#47]
Now that we have vignettes, perhaps it it time to abandon the old URL: http://lahman.r-forge.r-project.org/ in the package DESCRIPTION.

One main thing that might be interesting there is the link http://lahman.r-forge.r-project.org/doc/ to an old version of the package documentation, with results of all examples.  This could be redone using `pkgdown`, and then the URL changed to a github.io based version.

There might be a few other links worth preserving.

My sense is that if we do this, it should be after the CRAN release of v.7.0-0
Thoughts?

**Comment by cdalzell** [comment]
In the 2019 data update branch I've updated a couple of places to point to the [CRAN docs for the Lahman package](https://cran.r-project.org/web/packages/Lahman/Lahman.pdf). I've updated Github project header as well.
