### ISSUE TITLE
Documentation for lgID

### ISSUE THREAD

**Issue by jestarr** [cdalzell/Lahman#49]
Can someone tell me what "ML" in lgID stands for?  AL & NL are self-explanatory.

**Comment by cdalzell** [comment]
Sorry for the severely delayed response but for future searchers it stands for "Major League", shorthand for MLB.

Example: From 1956-1966 the Cy Young Award was given to a single player, not players in both the NL/AL as we do now.

https://en.wikipedia.org/wiki/Cy_Young_Award#Major_Leagues_combined_(1956%E2%80%931966)
