### ISSUE TITLE
It is time to release v8.0-0

### ISSUE THREAD

**Issue by friendly** [cdalzell/Lahman#52]
We had some conversation about the new release, but this got lost with covid & other things. Baseball season is on hold, but the Lahman pkg can still go forward.

Perhaps @cdalzell can remind us of the steps we need to do.  AFAICS, the current version, with all updated data since the last release in on the release v8/0-0 branch

**Comment by cdalzell** [comment]
Branch still seems ready to go, I'm ready to submit to CRAN if everyone else is.
