### ISSUE TITLE
Prune some old branches

### ISSUE THREAD

**Issue by friendly** [cdalzell/Lahman#53]
Late Spring cleaning:
We have quite a few old dead branches on the repo tree.  

Time to clean them up.  I can do this, but wanted to check with @cdalzell first, in case any old ones should be preserved for any reason.

**Comment by cdalzell** [comment]
I've just blown away quite a few of them, but there's one called `vignettes` I'm not sure about.

Is that a place for future vignette work? If so I'll get it caught up with `master`, if not I can delete it.

**Comment by cdalzell** [comment]
Branch deleted. If they need a new one new branches are easy and free. :)
