### ISSUE TITLE
downloading 2019

### ISSUE THREAD

**Issue by blottb7** [cdalzell/Lahman#57]
I was unable to download 2019 data with the provided link: install_github("cdalzell/Lahman", ref="insert_branch_name_here") after trying various branches. I received this error message: Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/cdalzell/Lahman/tarball/...' 
I WAS able to download 2019 simply using: install_github("cdalzell/Lahman")

**Comment by cdalzell** [comment]
Sorry for the delayed response, have you tried to pull the latest version from CRAN?

**Comment by friendly** [comment]
That bit in the README was generic. Since master has been released to CRAN,,I'll ammendthat to be less confusing
